In [3]:
!pip install -q imbalanced-learn

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import os

base_path = "/content/drive/MyDrive"

for root, dirs, files in os.walk(base_path):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

/content/drive/MyDrive/UNSW-NB15/NUSW-NB15_features.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_1.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_2.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_3.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_4.csv

In [6]:
dataset_path = "/content/drive/MyDrive/UNSW-NB15"

In [7]:
import os
import glob

files = []

for i in range(1, 5):
    file_path = os.path.join(
        dataset_path,
        f"UNSW-NB15_{i}.csv"
    )
    files.append(file_path)

print("Files to load:")

for file in files:
    print(file)

Files to load:
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_1.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_2.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_3.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_4.csv

In [8]:
import pandas as pd

dfs = []

for file in files:
    print("Loading:", os.path.basename(file))

    df_temp = pd.read_csv(file)

    print("Shape:", df_temp.shape)

    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

print("\nFinal dataset shape:", df.shape)

Loading: UNSW-NB15_1.csv

/tmp/ipykernel_5453/4036988093.py:8: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(file)

Shape: (700000, 49)
Loading: UNSW-NB15_2.csv

/tmp/ipykernel_5453/4036988093.py:8: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(file)

Shape: (700000, 49)
Loading: UNSW-NB15_3.csv
Shape: (700000, 49)
Loading: UNSW-NB15_4.csv
Shape: (440043, 49)

Final dataset shape: (2540043, 139)

In [9]:
import pandas as pd
import glob
import os

dataset_path = "/content/drive/MyDrive/UNSW-NB15"

files = glob.glob(os.path.join(dataset_path, "*.csv"))

print("Files found:")
for f in files:
    print(f)

Files found:
/content/drive/MyDrive/UNSW-NB15/NUSW-NB15_features.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_1.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_2.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_3.csv
/content/drive/MyDrive/UNSW-NB15/UNSW-NB15_4.csv

In [10]:
print(df.head())

   59.166.0.0   1390  149.171.126.6    53  udp  CON  0.001055    132    164  \
0  59.166.0.0  33661  149.171.126.9  1024  udp  CON  0.036133  528.0  304.0
1  59.166.0.6   1464  149.171.126.7    53  udp  CON  0.001119  146.0  178.0
2  59.166.0.5   3593  149.171.126.5    53  udp  CON  0.001209  132.0  164.0
3  59.166.0.3  49664  149.171.126.0    53  udp  CON  0.001169  146.0  178.0
4  59.166.0.0  32119  149.171.126.9   111  udp  CON  0.078339  568.0  312.0

   31  ...  456.043567  15.530109  1424250009 1424250009.1  3.943843  \
0  31  ...         NaN        NaN         NaN          NaN       NaN
1  31  ...         NaN        NaN         NaN          NaN       NaN
2  31  ...         NaN        NaN         NaN          NaN       NaN
3  31  ...         NaN        NaN         NaN          NaN       NaN
4  31  ...         NaN        NaN         NaN          NaN       NaN

   4.912488  0.00059  0.000473  0.000117   4
0       NaN      NaN       NaN       NaN NaN
1       NaN      NaN       NaN       NaN NaN
2       NaN      NaN       NaN       NaN NaN
3       NaN      NaN       NaN       NaN NaN
4       NaN      NaN       NaN       NaN NaN

[5 rows x 139 columns]

In [11]:
print(df.columns.tolist())

['59.166.0.0', '1390', '149.171.126.6', '53', 'udp', 'CON', '0.001055', '132', '164', '31', '29', '0', '0.1', 'dns', '500473.9375', '621800.9375', '2', '2.1', '0.2', '0.3', '0.4', '0.5', '66', '82', '0.6', '0.7', '0.8', '0.9', '1421927414', '1421927414.1', '0.017', '0.013', '0.10', '0.11', '0.12', '0.13', '0.14', '0.15', '0.16', '0.17', '3', '7', '1', '3.1', '1.1', '1.2', '1.3', 'Unnamed: 47', '0.18', '6055', '149.171.126.5', '54145', 'tcp', 'FIN', '0.072974', '4238', '60788', '30', '-', '458245.4375', '6571546.5', '72', '72.1', '255', '255.1', '1003293149', '1003585034', '59', '844', '62.04531', '61.899776', '1421955842', '1421955842.1', '1.02269', '0.997042', '0.002317', '0.002173', '0.000144', '13', '13.1', '6', '7.1', '59.166.0.1', '18247', '149.171.126.4', '7662', '0.119596', '4550', '68342', '33', '300478.2813', '4514398.5', '78', '80', '1818376620', '1818657356', '58', '854', '87.137592', '85.643619', '1424231129', '1424231129.1', '1.549156', '1.50719', '0.000644', '0.000521', '0.000123', 'Unnamed: 37', 'Unnamed: 38', ' ', '5', '2.2', '59.166.0.9', '7045', '149.171.126.7', '25', '0.201886', '37552', '3380', '18', '8', 'smtp', '1459437.5', '130766.8672', '52', '42', '1422136554', '3572668484', '722', '456.043567', '15.530109', '1424250009', '1424250009.1', '3.943843', '4.912488', '0.00059', '0.000473', '0.000117', '4']

In [12]:
print(df.shape)

(2540043, 139)

In [13]:
print("Number of columns:", len(df.columns))
print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nShape:")
print(df.shape)

Number of columns: 139

Column names:
['59.166.0.0', '1390', '149.171.126.6', '53', 'udp', 'CON', '0.001055', '132', '164', '31', '29', '0', '0.1', 'dns', '500473.9375', '621800.9375', '2', '2.1', '0.2', '0.3', '0.4', '0.5', '66', '82', '0.6', '0.7', '0.8', '0.9', '1421927414', '1421927414.1', '0.017', '0.013', '0.10', '0.11', '0.12', '0.13', '0.14', '0.15', '0.16', '0.17', '3', '7', '1', '3.1', '1.1', '1.2', '1.3', 'Unnamed: 47', '0.18', '6055', '149.171.126.5', '54145', 'tcp', 'FIN', '0.072974', '4238', '60788', '30', '-', '458245.4375', '6571546.5', '72', '72.1', '255', '255.1', '1003293149', '1003585034', '59', '844', '62.04531', '61.899776', '1421955842', '1421955842.1', '1.02269', '0.997042', '0.002317', '0.002173', '0.000144', '13', '13.1', '6', '7.1', '59.166.0.1', '18247', '149.171.126.4', '7662', '0.119596', '4550', '68342', '33', '300478.2813', '4514398.5', '78', '80', '1818376620', '1818657356', '58', '854', '87.137592', '85.643619', '1424231129', '1424231129.1', '1.549156', '1.50719', '0.000644', '0.000521', '0.000123', 'Unnamed: 37', 'Unnamed: 38', ' ', '5', '2.2', '59.166.0.9', '7045', '149.171.126.7', '25', '0.201886', '37552', '3380', '18', '8', 'smtp', '1459437.5', '130766.8672', '52', '42', '1422136554', '3572668484', '722', '456.043567', '15.530109', '1424250009', '1424250009.1', '3.943843', '4.912488', '0.00059', '0.000473', '0.000117', '4']

First 5 rows:

,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,456.043567,15.530109,1424250009,1424250009.1,3.943843,4.912488,0.00059,0.000473,0.000117,4
0,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528.0,304.0,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146.0,178.0,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132.0,164.0,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146.0,178.0,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,59.166.0.0,32119,149.171.126.9,111,udp,CON,0.078339,568.0,312.0,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Shape:
(2540043, 139)

In [14]:
features_path = "/content/drive/MyDrive/UNSW-NB15/NUSW-NB15_features.csv"

# Try a compatible encoding
features_df = pd.read_csv(
    features_path,
    encoding="cp1252"
)

print("Features file shape:", features_df.shape)
display(features_df.head(20))
print(features_df.columns.tolist())

Features file shape: (49, 4)

    No.     Name    Type                                         Description
0     1    srcip  nominal                                  Source IP address
1     2    sport  integer                                 Source port number
2     3    dstip  nominal                             Destination IP address
3     4   dsport  integer                            Destination port number
4     5    proto  nominal                               Transaction protocol
5     6    state  nominal  Indicates to the state and its dependent proto...
6     7      dur    Float                              Record total duration
7     8   sbytes  Integer           Source to destination transaction bytes
8     9   dbytes  Integer            Destination to source transaction bytes
9    10     sttl  Integer          Source to destination time to live value
10   11     dttl  Integer           Destination to source time to live value
11   12    sloss  Integer           Source packets retransmitted or dropped
12   13    dloss  Integer       Destination packets retransmitted or dropped
13   14  service  nominal  http, ftp, smtp, ssh, dns, ftp-data ,irc  and ...
14   15    Sload    Float                             Source bits per second
15   16    Dload    Float                        Destination bits per second
16   17    Spkts  integer                Source to destination packet count
17   18    Dpkts  integer                 Destination to source packet count
18   19     swin  integer              Source TCP window advertisement value
19   20     dwin  integer         Destination TCP window advertisement value

['No.', 'Name', 'Type ', 'Description']

In [15]:
print(features_df.to_string())

    No.              Name      Type                                                                                                                                                          Description
0     1             srcip    nominal                                                                                                                                                   Source IP address
1     2             sport    integer                                                                                                                                                  Source port number
2     3             dstip    nominal                                                                                                                                              Destination IP address
3     4            dsport    integer                                                                                                                                             Destination port number
4     5             proto    nominal                                                                                                                                                Transaction protocol
5     6             state    nominal      Indicates to the state and its dependent protocol, e.g. ACC, CLO, CON, ECO, ECR, FIN, INT, MAS, PAR, REQ, RST, TST, TXD, URH, URN, and (-) (if not used state)
6     7               dur      Float                                                                                                                                               Record total duration
7     8            sbytes    Integer                                                                                                                            Source to destination transaction bytes
8     9            dbytes    Integer                                                                                                                             Destination to source transaction bytes
9    10              sttl    Integer                                                                                                                           Source to destination time to live value
10   11              dttl    Integer                                                                                                                            Destination to source time to live value
11   12             sloss    Integer                                                                                                                            Source packets retransmitted or dropped
12   13             dloss    Integer                                                                                                                        Destination packets retransmitted or dropped
13   14           service    nominal                                                                                          http, ftp, smtp, ssh, dns, ftp-data ,irc  and (-) if not much used service
14   15             Sload      Float                                                                                                                                              Source bits per second
15   16             Dload      Float                                                                                                                                         Destination bits per second
16   17             Spkts    integer                                                                                                                                 Source to destination packet count
17   18             Dpkts    integer                                                                                                                                  Destination to source packet count
18   19              swin    integer                                                                                                                               Source TCP window advertisement value
19   20              dwin    integer                                                                                                                          Destination TCP window advertisement value
20   21             stcpb    integer                                                                                                                                     Source TCP base sequence number
21   22             dtcpb    integer                                                                                                                                Destination TCP base sequence number
22   23           smeansz    integer                                                                                                                 Mean of the ?ow packet size transmitted by the src
23   24           dmeansz    integer                                                                                                                 Mean of the ?ow packet size transmitted by the dst
24   25       trans_depth    integer                                                                             Represents the pipelined depth into the connection of http request/response transaction
25   26       res_bdy_len    integer                                                                            Actual uncompressed content size of the data transferred from the server’s http service.
26   27              Sjit      Float                                                                                                                                                Source jitter (mSec)
27   28              Djit      Float                                                                                                                                           Destination jitter (mSec)
28   29             Stime  Timestamp                                                                                                                                                   record start time
29   30             Ltime  Timestamp                                                                                                                                                    record last time
30   31           Sintpkt      Float                                                                                                                              Source interpacket arrival time (mSec)
31   32           Dintpkt      Float                                                                                                                         Destination interpacket arrival time (mSec)
32   33            tcprtt      Float                                                                                             TCP connection setup round-trip time, the sum of ’synack’ and ’ackdat’.
33   34            synack      Float                                                                                        TCP connection setup time, the time between the SYN and the SYN_ACK packets.
34   35            ackdat      Float                                                                                        TCP connection setup time, the time between the SYN_ACK and the ACK packets.
35   36   is_sm_ips_ports     Binary                                         If source (1) and destination (3)IP addresses equal and port numbers (2)(4)  equal then, this variable takes value 1 else 0
36   37      ct_state_ttl    Integer                                                         No. for each state (6) according to specific range of values for source/destination time to live (10) (11).
37   38  ct_flw_http_mthd    Integer                                                                                                 No. of flows that has methods such as Get and Post in http service.
38   39      is_ftp_login     Binary                                                                                                 If the ftp session is accessed by user and password then 1 else 0.
39   40        ct_ftp_cmd    integer                                                                                                                      No of flows that has a command in ftp session.
40   41        ct_srv_src    integer                                    No. of connections that contain the same service (14) and source address (1) in 100 connections according to the last time (26).
41   42        ct_srv_dst    integer                               No. of connections that contain the same service (14) and destination address (3) in 100 connections according to the last time (26).
42   43        ct_dst_ltm    integer                                                          No. of connections of the same destination address (3) in 100 connections according to the last time (26).
43   44       ct_src_ ltm    integer                                                               No. of connections of the same source address (1) in 100 connections according to the last time (26).
44   45  ct_src_dport_ltm    integer                                   No of connections of the same source address (1) and the destination port (4) in 100 connections according to the last time (26).
45   46  ct_dst_sport_ltm    integer                                   No of connections of the same destination address (3) and the source port (2) in 100 connections according to the last time (26).
46   47    ct_dst_src_ltm    integer                                     No of connections of the same source (1) and the destination (3) address in in 100 connections according to the last time (26).
47   48        attack_cat    nominal  The name of each attack category. In this data set , nine categories e.g. Fuzzers, Analysis, Backdoors, DoS Exploits, Generic, Reconnaissance, Shellcode and Worms
48   49             Label     binary                                                                                                                               0 for normal and 1 for attack records

In [16]:
import pandas as pd
import os

dataset_path = "/content/drive/MyDrive/UNSW-NB15"

files = [
    os.path.join(dataset_path, "UNSW-NB15_1.csv"),
    os.path.join(dataset_path, "UNSW-NB15_2.csv"),
    os.path.join(dataset_path, "UNSW-NB15_3.csv"),
    os.path.join(dataset_path, "UNSW-NB15_4.csv")
]

# Correct 49 column names from the UNSW-NB15 features file
columns = [
    "srcip", "sport", "dstip", "dsport", "proto", "state",
    "dur", "sbytes", "dbytes", "sttl", "dttl", "sloss", "dloss",
    "service", "Sload", "Dload", "Spkts", "Dpkts", "swin", "dwin",
    "stcpb", "dtcpb", "smeansz", "dmeansz", "trans_depth",
    "res_bdy_len", "Sjit", "Djit", "Stime", "Ltime",
    "Sintpkt", "Dintpkt", "tcprtt", "synack", "ackdat",
    "is_sm_ips_ports", "ct_state_ttl", "ct_flw_http_mthd",
    "is_ftp_login", "ct_ftp_cmd", "ct_srv_src", "ct_srv_dst",
    "ct_dst_ltm", "ct_src_ltm", "ct_src_dport_ltm",
    "ct_dst_sport_ltm", "ct_dst_src_ltm", "attack_cat", "Label"
]

dfs = []

for file in files:
    print("Loading:", os.path.basename(file))

    temp = pd.read_csv(
        file,
        header=None,
        names=columns,
        encoding="latin1"
    )

    print("Shape:", temp.shape)
    dfs.append(temp)

# Combine all four files
df = pd.concat(dfs, ignore_index=True)

print("\nFinal dataset shape:", df.shape)
print("\nColumns:", len(df.columns))
print(df.columns.tolist())

Loading: UNSW-NB15_1.csv

/tmp/ipykernel_5453/2093189942.py:32: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(

Shape: (700001, 49)
Loading: UNSW-NB15_2.csv

/tmp/ipykernel_5453/2093189942.py:32: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(

Shape: (700001, 49)
Loading: UNSW-NB15_3.csv
Shape: (700001, 49)
Loading: UNSW-NB15_4.csv
Shape: (440044, 49)

Final dataset shape: (2540047, 49)

Columns: 49
['srcip', 'sport', 'dstip', 'dsport', 'proto', 'state', 'dur', 'sbytes', 'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'service', 'Sload', 'Dload', 'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Stime', 'Ltime', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat', 'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_ftp_cmd', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'attack_cat', 'Label']

In [17]:
print(df["attack_cat"].value_counts(dropna=False))

attack_cat
NaN                 2218764
Generic              215481
Exploits              44525
 Fuzzers              19195
DoS                   16353
 Reconnaissance       12228
 Fuzzers               5051
Analysis               2677
Backdoor               1795
Reconnaissance         1759
 Shellcode             1288
Backdoors               534
Shellcode               223
Worms                   174
Name: count, dtype: int64

In [18]:
print("\nBinary Label:")
print(df["Label"].value_counts(dropna=False))

Binary Label:
Label
0    2218764
1     321283
Name: count, dtype: int64

In [19]:
print("\nUnique attack categories:")
print(df["attack_cat"].unique())

Unique attack categories:
[nan 'Exploits' 'Reconnaissance' 'DoS' 'Generic' 'Shellcode' ' Fuzzers'
 'Worms' 'Backdoors' 'Analysis' ' Reconnaissance ' 'Backdoor' ' Fuzzers '
 ' Shellcode ']

In [20]:
print("Missing attack_cat:", df["attack_cat"].isna().sum())
print("Empty attack_cat:", (df["attack_cat"].astype(str).str.strip() == "").sum())

Missing attack_cat: 2218764
Empty attack_cat: 0

In [21]:
df["attack_cat"] = df["attack_cat"].astype(str).str.strip()

df = df[
    df["attack_cat"].notna() &
    (df["attack_cat"] != "") &
    (df["attack_cat"].str.lower() != "nan")
].copy()

In [22]:
print(df["attack_cat"].value_counts())

attack_cat
Generic           215481
Exploits           44525
Fuzzers            24246
DoS                16353
Reconnaissance     13987
Analysis            2677
Backdoor            1795
Shellcode           1511
Backdoors            534
Worms                174
Name: count, dtype: int64

In [23]:
# Make a copy
df_bal = df.copy()

# Missing attack category = Normal
df_bal["attack_cat"] = df_bal["attack_cat"].fillna("Normal")

# Remove leading/trailing spaces
df_bal["attack_cat"] = df_bal["attack_cat"].astype(str).str.strip()

# Combine Backdoor and Backdoors
df_bal["attack_cat"] = df_bal["attack_cat"].replace({
    "Backdoor": "Backdoors"
})

# Check final classes
print(df_bal["attack_cat"].value_counts())

attack_cat
Generic           215481
Exploits           44525
Fuzzers            24246
DoS                16353
Reconnaissance     13987
Analysis            2677
Backdoors           2329
Shellcode           1511
Worms                174
Name: count, dtype: int64

In [24]:
print("\nNumber of classes:", df_bal["attack_cat"].nunique())

print("\nClass distribution:")
print(df_bal["attack_cat"].value_counts())

print("\nTotal records:")
print(len(df_bal))

Number of classes: 9

Class distribution:
attack_cat
Generic           215481
Exploits           44525
Fuzzers            24246
DoS                16353
Reconnaissance     13987
Analysis            2677
Backdoors           2329
Shellcode           1511
Worms                174
Name: count, dtype: int64

Total records:
321283

In [25]:
X = df_bal.drop(columns=["attack_cat", "Label"])
y = df_bal["attack_cat"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (321283, 47)
y shape: (321283,)

In [26]:
drop_cols = [
    "srcip",
    "dstip",
    "Stime",
    "Ltime"
]

X = X.drop(columns=drop_cols, errors="ignore")

print("Remaining features:", X.shape[1])
print(X.columns.tolist())

Remaining features: 43
['sport', 'dsport', 'proto', 'state', 'dur', 'sbytes', 'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'service', 'Sload', 'Dload', 'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat', 'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_ftp_cmd', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm']

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

Training set: (257026, 43)
Test set: (64257, 43)

In [28]:
print("\nTraining distribution:")
print(y_train.value_counts())

print("\nTest distribution:")
print(y_test.value_counts())

Training distribution:
attack_cat
Generic           172384
Exploits           35620
Fuzzers            19397
DoS                13082
Reconnaissance     11190
Analysis            2142
Backdoors           1863
Shellcode           1209
Worms                139
Name: count, dtype: int64

Test distribution:
attack_cat
Generic           43097
Exploits           8905
Fuzzers            4849
DoS                3271
Reconnaissance     2797
Analysis            535
Backdoors           466
Shellcode           302
Worms                35
Name: count, dtype: int64

In [29]:
categorical_cols = X_train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numerical_cols = X_train.select_dtypes(
    exclude=["object", "category"]
).columns.tolist()

print("Categorical columns:")
print(categorical_cols)

print("\nNumerical columns:")
print(numerical_cols)

Categorical columns:
['sport', 'dsport', 'proto', 'state', 'service', 'ct_ftp_cmd']

Numerical columns:
['dur', 'sbytes', 'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'Sload', 'Dload', 'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat', 'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm']

In [30]:
from sklearn.preprocessing import OrdinalEncoder

# Make categorical columns consistently string
X_train_enc = X_train.copy()
X_test_enc = X_test.copy()

for col in categorical_cols:
    X_train_enc[col] = X_train_enc[col].fillna("missing").astype(str)
    X_test_enc[col] = X_test_enc[col].fillna("missing").astype(str)

# Create encoder
encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

# Fit only on training data
X_train_enc[categorical_cols] = encoder.fit_transform(
    X_train_enc[categorical_cols]
)

# Transform test data using the same encoder
X_test_enc[categorical_cols] = encoder.transform(
    X_test_enc[categorical_cols]
)

print("Categorical encoding completed successfully.")
print("\nCategorical columns:")
print(categorical_cols)

print("\nTraining shape:", X_train_enc.shape)
print("Testing shape:", X_test_enc.shape)

Categorical encoding completed successfully.

Categorical columns:
['sport', 'dsport', 'proto', 'state', 'service', 'ct_ftp_cmd']

Training shape: (257026, 43)
Testing shape: (64257, 43)

In [31]:
print(X_train_enc[categorical_cols].head())
print("\nData types:")
print(X_train_enc[categorical_cols].dtypes)

           sport  dsport  proto  state  service  ct_ftp_cmd
2436215  21811.0  1615.0  115.0    3.0      2.0         0.0
2161920  21811.0  1615.0  115.0    3.0      2.0         0.0
1448547    254.0  1615.0  115.0    3.0      2.0         0.0
1465071  21811.0  1615.0  115.0    3.0      2.0         0.0
1515508    254.0  1615.0  115.0    3.0      2.0         0.0

Data types:
sport         float64
dsport        float64
proto         float64
state         float64
service       float64
ct_ftp_cmd    float64
dtype: object

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_enc[numerical_cols] = scaler.fit_transform(
    X_train_enc[numerical_cols]
)

X_test_enc[numerical_cols] = scaler.transform(
    X_test_enc[numerical_cols]
)

print("Numerical scaling completed.")

Numerical scaling completed.

In [33]:
categorical_indices = [
    X_train_enc.columns.get_loc(col)
    for col in categorical_cols
]

print("Categorical indices:", categorical_indices)

Categorical indices: [0, 1, 2, 3, 11, 35]

In [34]:
print("Training class distribution:")
print(y_train.value_counts())

print("\nCategorical columns:")
print(categorical_cols)

print("\nTotal training samples:", len(X_train_enc))

Training class distribution:
attack_cat
Generic           172384
Exploits           35620
Fuzzers            19397
DoS                13082
Reconnaissance     11190
Analysis            2142
Backdoors           1863
Shellcode           1209
Worms                139
Name: count, dtype: int64

Categorical columns:
['sport', 'dsport', 'proto', 'state', 'service', 'ct_ftp_cmd']

Total training samples: 257026

In [35]:
# Recreate the target AFTER cleaning

X = df_bal.drop(columns=["attack_cat", "Label"])
y = df_bal["attack_cat"]

print("All classes:")
print(y.value_counts())

print("\nNumber of classes:", y.nunique())

All classes:
attack_cat
Generic           215481
Exploits           44525
Fuzzers            24246
DoS                16353
Reconnaissance     13987
Analysis            2677
Backdoors           2329
Shellcode           1511
Worms                174
Name: count, dtype: int64

Number of classes: 9

In [36]:
# Start from the correctly loaded raw dataset
df_bal = df.copy()

# IMPORTANT:
# Missing attack_cat values in UNSW-NB15 correspond to Normal traffic
df_bal["attack_cat"] = df_bal["attack_cat"].fillna("Normal")

# Clean whitespace
df_bal["attack_cat"] = df_bal["attack_cat"].astype(str).str.strip()

# Combine the two spellings into one class
df_bal["attack_cat"] = df_bal["attack_cat"].replace({
    "Backdoor": "Backdoors"
})

# Check classes
print("Class distribution:")
print(df_bal["attack_cat"].value_counts())

print("\nNumber of classes:", df_bal["attack_cat"].nunique())

Class distribution:
attack_cat
Generic           215481
Exploits           44525
Fuzzers            24246
DoS                16353
Reconnaissance     13987
Analysis            2677
Backdoors           2329
Shellcode           1511
Worms                174
Name: count, dtype: int64

Number of classes: 9

In [37]:
import pandas as pd
import os

dataset_path = "/content/drive/MyDrive/UNSW-NB15"

files = [
    os.path.join(dataset_path, "UNSW-NB15_1.csv"),
    os.path.join(dataset_path, "UNSW-NB15_2.csv"),
    os.path.join(dataset_path, "UNSW-NB15_3.csv"),
    os.path.join(dataset_path, "UNSW-NB15_4.csv")
]

columns = [
    "srcip", "sport", "dstip", "dsport", "proto", "state",
    "dur", "sbytes", "dbytes", "sttl", "dttl", "sloss", "dloss",
    "service", "Sload", "Dload", "Spkts", "Dpkts", "swin", "dwin",
    "stcpb", "dtcpb", "smeansz", "dmeansz", "trans_depth",
    "res_bdy_len", "Sjit", "Djit", "Stime", "Ltime",
    "Sintpkt", "Dintpkt", "tcprtt", "synack", "ackdat",
    "is_sm_ips_ports", "ct_state_ttl", "ct_flw_http_mthd",
    "is_ftp_login", "ct_ftp_cmd", "ct_srv_src", "ct_srv_dst",
    "ct_dst_ltm", "ct_src_ltm", "ct_src_dport_ltm",
    "ct_dst_sport_ltm", "ct_dst_src_ltm", "attack_cat", "Label"
]

dfs = []

for file in files:
    temp = pd.read_csv(
        file,
        header=None,
        names=columns,
        encoding="latin1"
    )

    print(os.path.basename(file), temp.shape)
    print("Missing attack_cat:", temp["attack_cat"].isna().sum())

    dfs.append(temp)

# IMPORTANT: create a completely fresh dataframe
df_raw = pd.concat(dfs, ignore_index=True)

print("\n===================================")
print("RAW DATASET")
print("===================================")
print("Shape:", df_raw.shape)
print("Missing attack_cat:", df_raw["attack_cat"].isna().sum())
print("Non-missing attack_cat:", df_raw["attack_cat"].notna().sum())

/tmp/ipykernel_5453/2776726914.py:29: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(

UNSW-NB15_1.csv (700001, 49)
Missing attack_cat: 677786

/tmp/ipykernel_5453/2776726914.py:29: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(

UNSW-NB15_2.csv (700001, 49)
Missing attack_cat: 647252
UNSW-NB15_3.csv (700001, 49)
Missing attack_cat: 542576
UNSW-NB15_4.csv (440044, 49)
Missing attack_cat: 351150

===================================
RAW DATASET
===================================
Shape: (2540047, 49)
Missing attack_cat: 2218764
Non-missing attack_cat: 321283

In [38]:
df_bal = df_raw.copy()

# Missing attack category = Normal
df_bal["attack_cat"] = df_bal["attack_cat"].fillna("Normal")

# Clean category names
df_bal["attack_cat"] = df_bal["attack_cat"].astype(str).str.strip()

# Combine inconsistent Backdoor naming
df_bal["attack_cat"] = df_bal["attack_cat"].replace({
    "Backdoor": "Backdoors"
})

print("===================================")
print("FINAL 10-CLASS DISTRIBUTION")
print("===================================")

print(df_bal["attack_cat"].value_counts())

print("\nNumber of classes:", df_bal["attack_cat"].nunique())

print("\nTotal records:", len(df_bal))

===================================
FINAL 10-CLASS DISTRIBUTION
===================================
attack_cat
Normal            2218764
Generic            215481
Exploits            44525
Fuzzers             24246
DoS                 16353
Reconnaissance      13987
Analysis             2677
Backdoors            2329
Shellcode            1511
Worms                 174
Name: count, dtype: int64

Number of classes: 10

Total records: 2540047

In [39]:
# Create working dataset from the FRESH raw dataset
df_bal = df_raw.copy()

# In this UNSW-NB15 version, missing attack_cat corresponds to Normal traffic
df_bal["attack_cat"] = df_bal["attack_cat"].fillna("Normal")

# Clean category names
df_bal["attack_cat"] = df_bal["attack_cat"].astype(str).str.strip()

# Combine Backdoor and Backdoors
df_bal["attack_cat"] = df_bal["attack_cat"].replace({
    "Backdoor": "Backdoors"
})

# Check class distribution
print("Class Distribution:")
print(df_bal["attack_cat"].value_counts())

print("\nNumber of classes:", df_bal["attack_cat"].nunique())
print("Total records:", len(df_bal))

Class Distribution:
attack_cat
Normal            2218764
Generic            215481
Exploits            44525
Fuzzers             24246
DoS                 16353
Reconnaissance      13987
Analysis             2677
Backdoors            2329
Shellcode            1511
Worms                 174
Name: count, dtype: int64

Number of classes: 10
Total records: 2540047

In [40]:
# Separate input features and target
X = df_bal.drop(columns=["attack_cat", "Label"])
y = df_bal["attack_cat"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

X shape: (2540047, 47)
y shape: (2540047,)

Target distribution:
attack_cat
Normal            2218764
Generic            215481
Exploits            44525
Fuzzers             24246
DoS                 16353
Reconnaissance      13987
Analysis             2677
Backdoors            2329
Shellcode            1511
Worms                 174
Name: count, dtype: int64

In [41]:
drop_cols = ["srcip", "dstip", "Stime", "Ltime"]

X = X.drop(columns=drop_cols)

print("New X shape:", X.shape)
print("\nRemaining columns:")
print(X.columns.tolist())

New X shape: (2540047, 43)

Remaining columns:
['sport', 'dsport', 'proto', 'state', 'dur', 'sbytes', 'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'service', 'Sload', 'Dload', 'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat', 'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_ftp_cmd', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm']

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

print("\nTraining distribution:")
print(y_train.value_counts())

print("\nTesting distribution:")
print(y_test.value_counts())

Training shape: (2032037, 43)
Testing shape: (508010, 43)

Training distribution:
attack_cat
Normal            1775011
Generic            172385
Exploits            35620
Fuzzers             19397
DoS                 13082
Reconnaissance      11189
Analysis             2142
Backdoors            1863
Shellcode            1209
Worms                 139
Name: count, dtype: int64

Testing distribution:
attack_cat
Normal            443753
Generic            43096
Exploits            8905
Fuzzers             4849
DoS                 3271
Reconnaissance      2798
Analysis             535
Backdoors            466
Shellcode            302
Worms                 35
Name: count, dtype: int64

In [43]:
categorical_cols = X_train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numerical_cols = X_train.select_dtypes(
    exclude=["object", "category"]
).columns.tolist()

print("Categorical columns:")
print(categorical_cols)

print("\nNumber of categorical columns:", len(categorical_cols))

print("\nNumerical columns:")
print(numerical_cols)

print("\nNumber of numerical columns:", len(numerical_cols))

Categorical columns:
['sport', 'dsport', 'proto', 'state', 'service', 'ct_ftp_cmd']

Number of categorical columns: 6

Numerical columns:
['dur', 'sbytes', 'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'Sload', 'Dload', 'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat', 'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm']

Number of numerical columns: 37

In [44]:
from sklearn.preprocessing import OrdinalEncoder

X_train_enc = X_train.copy()
X_test_enc = X_test.copy()

for col in categorical_cols:
    X_train_enc[col] = (
        X_train_enc[col]
        .fillna("missing")
        .astype(str)
    )

    X_test_enc[col] = (
        X_test_enc[col]
        .fillna("missing")
        .astype(str)
    )

encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

X_train_enc[categorical_cols] = encoder.fit_transform(
    X_train_enc[categorical_cols]
)

X_test_enc[categorical_cols] = encoder.transform(
    X_test_enc[categorical_cols]
)

print("Categorical encoding completed.")

Categorical encoding completed.

In [45]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_enc[numerical_cols] = scaler.fit_transform(
    X_train_enc[numerical_cols]
)

X_test_enc[numerical_cols] = scaler.transform(
    X_test_enc[numerical_cols]
)

print("Numerical scaling completed.")

Numerical scaling completed.

In [46]:
categorical_indices = [
    X_train_enc.columns.get_loc(col)
    for col in categorical_cols
]

print("Categorical indices:")
print(categorical_indices)

Categorical indices:
[0, 1, 2, 3, 11, 35]

In [47]:
!pip install -q imbalanced-learn

In [48]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTENC, RandomOverSampler

In [49]:
under_strategy = {
    "Normal": 150000,
    "Generic": 150000
}

under = RandomUnderSampler(
    sampling_strategy=under_strategy,
    random_state=42
)

X_under, y_under = under.fit_resample(
    X_train_enc,
    y_train
)

print("After undersampling:")
print(y_under.value_counts())
print("\nTotal:", len(y_under))

After undersampling:
attack_cat
Normal            150000
Generic           150000
Exploits           35620
Fuzzers            19397
DoS                13082
Reconnaissance     11189
Analysis            2142
Backdoors           1863
Shellcode           1209
Worms                139
Name: count, dtype: int64

Total: 384641

In [50]:
from imblearn.over_sampling import SMOTENC, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

print("SMOTENC imported successfully!")

SMOTENC imported successfully!

In [51]:
from sklearn.preprocessing import OrdinalEncoder

# Copy train and test data
X_train_enc = X_train.copy()
X_test_enc = X_test.copy()

# Categorical columns
categorical_cols = [
    'sport',
    'dsport',
    'proto',
    'state',
    'service',
    'ct_ftp_cmd'
]

# Convert categorical values to strings
for col in categorical_cols:
    X_train_enc[col] = X_train_enc[col].fillna("missing").astype(str)
    X_test_enc[col] = X_test_enc[col].fillna("missing").astype(str)

# Encode categorical columns
encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

X_train_enc[categorical_cols] = encoder.fit_transform(
    X_train_enc[categorical_cols]
)

X_test_enc[categorical_cols] = encoder.transform(
    X_test_enc[categorical_cols]
)

print("Encoding completed!")
print("X_train_enc shape:", X_train_enc.shape)
print("X_test_enc shape:", X_test_enc.shape)

Encoding completed!
X_train_enc shape: (2032037, 43)
X_test_enc shape: (508010, 43)

In [52]:
from sklearn.preprocessing import StandardScaler

numerical_cols = [
    col for col in X_train_enc.columns
    if col not in categorical_cols
]

scaler = StandardScaler()

X_train_enc[numerical_cols] = scaler.fit_transform(
    X_train_enc[numerical_cols]
)

X_test_enc[numerical_cols] = scaler.transform(
    X_test_enc[numerical_cols]
)

print("Scaling completed!")

Scaling completed!

In [53]:
categorical_indices = [
    X_train_enc.columns.get_loc(col)
    for col in categorical_cols
]

print("Categorical columns:")
print(categorical_cols)

print("\nCategorical indices:")
print(categorical_indices)

Categorical columns:
['sport', 'dsport', 'proto', 'state', 'service', 'ct_ftp_cmd']

Categorical indices:
[0, 1, 2, 3, 11, 35]

In [54]:
!pip install -q imbalanced-learn

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTENC, RandomOverSampler

print("Balancing libraries ready!")

Balancing libraries ready!

In [55]:
under_strategy = {
    "Normal": 150000,
    "Generic": 150000
}

under = RandomUnderSampler(
    sampling_strategy=under_strategy,
    random_state=42
)

X_under, y_under = under.fit_resample(
    X_train_enc,
    y_train
)

print("After undersampling:")
print(y_under.value_counts())

print("\nTotal samples:", len(y_under))

After undersampling:
attack_cat
Normal            150000
Generic           150000
Exploits           35620
Fuzzers            19397
DoS                13082
Reconnaissance     11189
Analysis            2142
Backdoors           1863
Shellcode           1209
Worms                139
Name: count, dtype: int64

Total samples: 384641

In [56]:
categorical_cols = [
    'sport',
    'dsport',
    'proto',
    'state',
    'service',
    'ct_ftp_cmd'
]

categorical_indices = [
    X_train_enc.columns.get_loc(col)
    for col in categorical_cols
]

print("Categorical columns:", categorical_cols)
print("Categorical indices:", categorical_indices)

Categorical columns: ['sport', 'dsport', 'proto', 'state', 'service', 'ct_ftp_cmd']
Categorical indices: [0, 1, 2, 3, 11, 35]

In [57]:
print("NaN values in X_under:")
nan_counts = X_under.isna().sum()

print(nan_counts[nan_counts > 0])
print("\nTotal NaN values:", X_under.isna().sum().sum())

NaN values in X_under:
ct_flw_http_mthd    277076
is_ftp_login        292771
dtype: int64

Total NaN values: 569847

In [58]:
# Create a copy
X_under_clean = X_under.copy()

# Fill numerical NaN values with median
for col in numerical_cols:
    median_value = X_under_clean[col].median()
    X_under_clean[col] = X_under_clean[col].fillna(median_value)

# Fill categorical NaN values
for col in categorical_cols:
    mode_value = X_under_clean[col].mode()[0]
    X_under_clean[col] = X_under_clean[col].fillna(mode_value)

print("NaN values after cleaning:")
print(X_under_clean.isna().sum().sum())

NaN values after cleaning:
0

In [59]:
print("X_under_clean shape:", X_under_clean.shape)
print("y_under shape:", y_under.shape)

print("\nClass distribution:")
print(y_under.value_counts())

print("\nTotal NaN:", X_under_clean.isna().sum().sum())

X_under_clean shape: (384641, 43)
y_under shape: (384641,)

Class distribution:
attack_cat
Normal            150000
Generic           150000
Exploits           35620
Fuzzers            19397
DoS                13082
Reconnaissance     11189
Analysis            2142
Backdoors           1863
Shellcode           1209
Worms                139
Name: count, dtype: int64

Total NaN: 0

In [ ]:
from imblearn.over_sampling import SMOTENC

smote_strategy = {
    "Exploits": 150000,
    "Fuzzers": 150000,
    "DoS": 150000,
    "Reconnaissance": 150000,
    "Analysis": 15000,
    "Backdoors": 15000,
    "Shellcode": 10000
}

smote = SMOTENC(
    categorical_features=categorical_indices,
    sampling_strategy=smote_strategy,
    random_state=42,
    k_neighbors=5
)

X_smote, y_smote = smote.fit_resample(
    X_under_clean,
    y_under
)

print("SMOTENC completed!")

print("\nDistribution after SMOTENC:")
print(y_smote.value_counts())

print("\nTotal samples:", len(y_smote))

In [2]:
# ============================================================
# UNSW-NB15 - SINGLE CELL MEMORY-SAFE BALANCING PIPELINE
# ============================================================

import os
import gc
import pandas as pd
from sklearn.model_selection import train_test_split

# ------------------------------------------------------------
# 1. MOUNT GOOGLE DRIVE
# ------------------------------------------------------------
from google.colab import drive
drive.mount('/content/drive')

# ------------------------------------------------------------
# 2. DATASET PATH
# ------------------------------------------------------------
dataset_path = "/content/drive/MyDrive/UNSW-NB15"

files = [
    os.path.join(dataset_path, "UNSW-NB15_1.csv"),
    os.path.join(dataset_path, "UNSW-NB15_2.csv"),
    os.path.join(dataset_path, "UNSW-NB15_3.csv"),
    os.path.join(dataset_path, "UNSW-NB15_4.csv")
]

# ------------------------------------------------------------
# 3. CORRECT 49 COLUMN NAMES
# ------------------------------------------------------------
columns = [
    "srcip", "sport", "dstip", "dsport", "proto", "state",
    "dur", "sbytes", "dbytes", "sttl", "dttl", "sloss", "dloss",
    "service", "Sload", "Dload", "Spkts", "Dpkts", "swin", "dwin",
    "stcpb", "dtcpb", "smeansz", "dmeansz", "trans_depth",
    "res_bdy_len", "Sjit", "Djit", "Stime", "Ltime",
    "Sintpkt", "Dintpkt", "tcprtt", "synack", "ackdat",
    "is_sm_ips_ports", "ct_state_ttl", "ct_flw_http_mthd",
    "is_ftp_login", "ct_ftp_cmd", "ct_srv_src", "ct_srv_dst",
    "ct_dst_ltm", "ct_src_ltm", "ct_src_dport_ltm",
    "ct_dst_sport_ltm", "ct_dst_src_ltm", "attack_cat", "Label"
]

# ------------------------------------------------------------
# 4. LOAD THE 4 RAW CSV FILES
#    IMPORTANT: These files have NO HEADER
# ------------------------------------------------------------
print("Loading UNSW-NB15 files...\n")

dfs = []

for file in files:

    print("Loading:", os.path.basename(file))

    temp = pd.read_csv(
        file,
        header=None,
        names=columns,
        encoding="latin1"
    )

    # Create Normal class from missing attack_cat
    temp["attack_cat"] = temp["attack_cat"].fillna("Normal")

    # Clean class names
    temp["attack_cat"] = (
        temp["attack_cat"]
        .astype(str)
        .str.strip()
        .replace({"Backdoor": "Backdoors"})
    )

    print("Rows:", len(temp))

    dfs.append(temp)

# ------------------------------------------------------------
# 5. COMBINE ALL FILES
# ------------------------------------------------------------
df = pd.concat(dfs, ignore_index=True)

# Free memory
del dfs
gc.collect()

print("\n========================================")
print("RAW DATASET")
print("========================================")
print("Shape:", df.shape)

print("\nClass distribution:")
print(df["attack_cat"].value_counts())

print("\nNumber of classes:", df["attack_cat"].nunique())

# ------------------------------------------------------------
# 6. REMOVE UNNECESSARY COLUMNS
# ------------------------------------------------------------
# IP addresses and timestamps are removed because:
# - They can cause high-cardinality problems
# - They are not useful as direct ML features
# Label is removed because attack_cat is our target

drop_cols = [
    "srcip",
    "dstip",
    "Stime",
    "Ltime",
    "Label"
]

df = df.drop(columns=drop_cols)

print("\nColumns after removal:", df.shape[1])

# ------------------------------------------------------------
# 7. TRAIN / TEST SPLIT
# ------------------------------------------------------------
# IMPORTANT:
# Split BEFORE balancing to prevent data leakage.
# Test data remains completely untouched.

print("\nCreating train/test split...")

train_df, test_df = train_test_split(
    df,
    test_size=0.20,
    random_state=42,
    stratify=df["attack_cat"]
)

# Free original dataframe
del df
gc.collect()

print("\n========================================")
print("BEFORE BALANCING")
print("========================================")

print("Training rows:", len(train_df))
print("Testing rows:", len(test_df))

print("\nTraining class distribution:")
print(train_df["attack_cat"].value_counts())

# ------------------------------------------------------------
# 8. TARGET COUNTS FOR BALANCING
# ------------------------------------------------------------
# Final training dataset = 660,000 rows
#
# Normal           100,000
# Generic          100,000
# Exploits         100,000
# Fuzzers          100,000
# DoS              100,000
# Reconnaissance   100,000
# Analysis          20,000
# Backdoors         20,000
# Shellcode         10,000
# Worms             10,000
#
# This uses:
# - Undersampling for large classes
# - Oversampling for small classes
#
# NO SMOTE / SMOTENC
# Therefore much lower memory usage.

targets = {
    "Normal": 100000,
    "Generic": 100000,
    "Exploits": 100000,
    "Fuzzers": 100000,
    "DoS": 100000,
    "Reconnaissance": 100000,
    "Analysis": 20000,
    "Backdoors": 20000,
    "Shellcode": 10000,
    "Worms": 10000
}

# ------------------------------------------------------------
# 9. BALANCE TRAINING DATA
# ------------------------------------------------------------
print("\n========================================")
print("BALANCING TRAINING DATA")
print("========================================")

balanced_parts = []

for cls, target_count in targets.items():

    class_data = train_df[train_df["attack_cat"] == cls]

    actual_count = len(class_data)

    if actual_count == 0:
        raise ValueError(
            f"ERROR: Class '{cls}' was not found in the dataset."
        )

    # Undersampling if class has more records
    # Oversampling if class has fewer records
    replace = actual_count < target_count

    sampled_data = class_data.sample(
        n=target_count,
        replace=replace,
        random_state=42
    )

    balanced_parts.append(sampled_data)

    method = "Oversampling" if replace else "Undersampling"

    print(
        f"{cls:18s} : "
        f"{actual_count:8,d} -> "
        f"{target_count:8,d}  ({method})"
    )

# ------------------------------------------------------------
# 10. COMBINE BALANCED CLASSES
# ------------------------------------------------------------
balanced_train = pd.concat(
    balanced_parts,
    ignore_index=True
)

# Free unnecessary objects
del balanced_parts
del train_df
gc.collect()

# Shuffle balanced dataset
balanced_train = balanced_train.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# ------------------------------------------------------------
# 11. FINAL DISTRIBUTIONS
# ------------------------------------------------------------
print("\n========================================")
print("FINAL BALANCED TRAINING DATA")
print("========================================")

print("Balanced shape:", balanced_train.shape)

print("\nBalanced class distribution:")
print(
    balanced_train["attack_cat"]
    .value_counts()
)

print("\n========================================")
print("TEST DATA - UNTOUCHED")
print("========================================")

print("Test shape:", test_df.shape)

print("\nTest class distribution:")
print(
    test_df["attack_cat"]
    .value_counts()
)

# ------------------------------------------------------------
# 12. SAVE BALANCED TRAIN + ORIGINAL TEST
# ------------------------------------------------------------
balanced_path = os.path.join(
    dataset_path,
    "UNSW_NB15_balanced_train.csv"
)

test_path = os.path.join(
    dataset_path,
    "UNSW_NB15_test.csv"
)

print("\nSaving balanced training dataset...")

balanced_train.to_csv(
    balanced_path,
    index=False
)

print("Balanced training dataset saved.")

print("\nSaving test dataset...")

test_df.to_csv(
    test_path,
    index=False
)

print("Test dataset saved.")

# ------------------------------------------------------------
# 13. FINAL SUMMARY
# ------------------------------------------------------------
print("\n\n================================================")
print("             PIPELINE COMPLETED")
print("================================================")

print("\nBalanced training dataset:")
print(balanced_path)

print("\nTest dataset:")
print(test_path)

print("\nTraining rows:", len(balanced_train))
print("Testing rows :", len(test_df))

print("\nNumber of classes:",
      balanced_train["attack_cat"].nunique())

print("\nFinal training distribution:")
print(
    balanced_train["attack_cat"]
    .value_counts()
    .sort_index()
)

print("\n================================================")
print("DONE")
print("================================================")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Loading UNSW-NB15 files...

Loading: UNSW-NB15_1.csv

/tmp/ipykernel_7583/1940953288.py:56: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(

Rows: 700001
Loading: UNSW-NB15_2.csv

/tmp/ipykernel_7583/1940953288.py:56: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(

Rows: 700001
Loading: UNSW-NB15_3.csv
Rows: 700001
Loading: UNSW-NB15_4.csv
Rows: 440044

========================================
RAW DATASET
========================================
Shape: (2540047, 49)

Class distribution:
attack_cat
Normal            2218764
Generic            215481
Exploits            44525
Fuzzers             24246
DoS                 16353
Reconnaissance      13987
Analysis             2677
Backdoors            2329
Shellcode            1511
Worms                 174
Name: count, dtype: int64

Number of classes: 10

Columns after removal: 44

Creating train/test split...

========================================
BEFORE BALANCING
========================================
Training rows: 2032037
Testing rows: 508010

Training class distribution:
attack_cat
Normal            1775011
Generic            172385
Exploits            35620
Fuzzers             19397
DoS                 13082
Reconnaissance      11189
Analysis             2142
Backdoors            1863
Shellcode            1209
Worms                 139
Name: count, dtype: int64

========================================
BALANCING TRAINING DATA
========================================
Normal             : 1,775,011 ->  100,000  (Undersampling)
Generic            :  172,385 ->  100,000  (Undersampling)
Exploits           :   35,620 ->  100,000  (Oversampling)
Fuzzers            :   19,397 ->  100,000  (Oversampling)
DoS                :   13,082 ->  100,000  (Oversampling)
Reconnaissance     :   11,189 ->  100,000  (Oversampling)
Analysis           :    2,142 ->   20,000  (Oversampling)
Backdoors          :    1,863 ->   20,000  (Oversampling)
Shellcode          :    1,209 ->   10,000  (Oversampling)
Worms              :      139 ->   10,000  (Oversampling)

========================================
FINAL BALANCED TRAINING DATA
========================================
Balanced shape: (660000, 44)

Balanced class distribution:
attack_cat
Fuzzers           100000
Normal            100000
Generic           100000
DoS               100000
Exploits          100000
Reconnaissance    100000
Backdoors          20000
Analysis           20000
Shellcode          10000
Worms              10000
Name: count, dtype: int64

========================================
TEST DATA - UNTOUCHED
========================================
Test shape: (508010, 44)

Test class distribution:
attack_cat
Normal            443753
Generic            43096
Exploits            8905
Fuzzers             4849
DoS                 3271
Reconnaissance      2798
Analysis             535
Backdoors            466
Shellcode            302
Worms                 35
Name: count, dtype: int64

Saving balanced training dataset...
Balanced training dataset saved.

Saving test dataset...
Test dataset saved.


================================================
             PIPELINE COMPLETED
================================================

Balanced training dataset:
/content/drive/MyDrive/UNSW-NB15/UNSW_NB15_balanced_train.csv

Test dataset:
/content/drive/MyDrive/UNSW-NB15/UNSW_NB15_test.csv

Training rows: 660000
Testing rows : 508010

Number of classes: 10

Final training distribution:
attack_cat
Analysis           20000
Backdoors          20000
DoS               100000
Exploits          100000
Fuzzers           100000
Generic           100000
Normal            100000
Reconnaissance    100000
Shellcode          10000
Worms              10000
Name: count, dtype: int64

================================================
DONE
================================================

In [3]:
# ============================================================
# VERIFY BALANCED UNSW-NB15 DATASET
# ============================================================

import os
import pandas as pd

dataset_path = "/content/drive/MyDrive/UNSW-NB15"

balanced_path = os.path.join(
    dataset_path,
    "UNSW_NB15_balanced_train.csv"
)

test_path = os.path.join(
    dataset_path,
    "UNSW_NB15_test.csv"
)

# Check files exist
print("Balanced file exists:", os.path.exists(balanced_path))
print("Test file exists    :", os.path.exists(test_path))

# Load only the target column first
balanced = pd.read_csv(
    balanced_path,
    usecols=["attack_cat"]
)

test = pd.read_csv(
    test_path,
    usecols=["attack_cat"]
)

print("\n========================================")
print("BALANCED TRAINING DATA")
print("========================================")
print("Rows:", len(balanced))
print("\nClass distribution:")
print(balanced["attack_cat"].value_counts().sort_index())

print("\n========================================")
print("TEST DATA")
print("========================================")
print("Rows:", len(test))
print("\nClass distribution:")
print(test["attack_cat"].value_counts().sort_index())

print("\n========================================")
print("CHECK")
print("========================================")

print(
    "\nNumber of training classes:",
    balanced["attack_cat"].nunique()
)

print(
    "Number of test classes:",
    test["attack_cat"].nunique()
)

Balanced file exists: True
Test file exists    : True

========================================
BALANCED TRAINING DATA
========================================
Rows: 660000

Class distribution:
attack_cat
Analysis           20000
Backdoors          20000
DoS               100000
Exploits          100000
Fuzzers           100000
Generic           100000
Normal            100000
Reconnaissance    100000
Shellcode          10000
Worms              10000
Name: count, dtype: int64

========================================
TEST DATA
========================================
Rows: 508010

Class distribution:
attack_cat
Analysis             535
Backdoors            466
DoS                 3271
Exploits            8905
Fuzzers             4849
Generic            43096
Normal            443753
Reconnaissance      2798
Shellcode            302
Worms                 35
Name: count, dtype: int64

========================================
CHECK
========================================

Number of training classes: 10
Number of test classes: 10

In [4]:
# ============================================================
# STEP 2: LOAD BALANCED DATA + INSPECT FEATURES
# ============================================================

import pandas as pd
import numpy as np
import os
import gc

dataset_path = "/content/drive/MyDrive/UNSW-NB15"

balanced_path = os.path.join(
    dataset_path,
    "UNSW_NB15_balanced_train.csv"
)

test_path = os.path.join(
    dataset_path,
    "UNSW_NB15_test.csv"
)

# ------------------------------------------------------------
# LOAD DATA
# ------------------------------------------------------------

print("Loading balanced training data...")

train_df = pd.read_csv(
    balanced_path,
    encoding="latin1"
)

print("Training data loaded.")

print("\nLoading test data...")

test_df = pd.read_csv(
    test_path,
    encoding="latin1"
)

print("Test data loaded.")

# ------------------------------------------------------------
# BASIC INFORMATION
# ------------------------------------------------------------

print("\n========================================")
print("DATASET SHAPES")
print("========================================")

print("Training shape:", train_df.shape)
print("Test shape    :", test_df.shape)

print("\n========================================")
print("COLUMN INFORMATION")
print("========================================")

print("Number of columns:", len(train_df.columns))

print("\nColumns:")
for i, col in enumerate(train_df.columns, start=1):
    print(f"{i:2d}. {col}")

# ------------------------------------------------------------
# DATA TYPES
# ------------------------------------------------------------

print("\n========================================")
print("DATA TYPES")
print("========================================")

print(train_df.dtypes)

# ------------------------------------------------------------
# CATEGORICAL COLUMNS
# ------------------------------------------------------------

categorical_cols = train_df.select_dtypes(
    include=["object"]
).columns.tolist()

print("\n========================================")
print("CATEGORICAL COLUMNS")
print("========================================")

print(categorical_cols)

# ------------------------------------------------------------
# NUMERICAL COLUMNS
# ------------------------------------------------------------

numerical_cols = [
    col for col in train_df.columns
    if col not in categorical_cols
]

print("\n========================================")
print("NUMERICAL COLUMNS")
print("========================================")

print("Number of numerical columns:",
      len(numerical_cols))

print(numerical_cols)

# ------------------------------------------------------------
# MISSING VALUES
# ------------------------------------------------------------

print("\n========================================")
print("MISSING VALUES")
print("========================================")

missing = train_df.isnull().sum()

missing = missing[missing > 0].sort_values(
    ascending=False
)

if len(missing) == 0:
    print("No missing values found.")
else:
    print(missing)

# ------------------------------------------------------------
# TARGET CHECK
# ------------------------------------------------------------

print("\n========================================")
print("TARGET")
print("========================================")

print("Target column: attack_cat")

print("\nTraining target distribution:")
print(
    train_df["attack_cat"]
    .value_counts()
    .sort_index()
)

print("\nTest target distribution:")
print(
    test_df["attack_cat"]
    .value_counts()
    .sort_index()
)

print("\n========================================")
print("STEP 2 COMPLETED")
print("========================================")

Loading balanced training data...

/tmp/ipykernel_7583/2872662051.py:28: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv(

Training data loaded.

Loading test data...

/tmp/ipykernel_7583/2872662051.py:37: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  test_df = pd.read_csv(

Test data loaded.

========================================
DATASET SHAPES
========================================
Training shape: (660000, 44)
Test shape    : (508010, 44)

========================================
COLUMN INFORMATION
========================================
Number of columns: 44

Columns:
 1. sport
 2. dsport
 3. proto
 4. state
 5. dur
 6. sbytes
 7. dbytes
 8. sttl
 9. dttl
10. sloss
11. dloss
12. service
13. Sload
14. Dload
15. Spkts
16. Dpkts
17. swin
18. dwin
19. stcpb
20. dtcpb
21. smeansz
22. dmeansz
23. trans_depth
24. res_bdy_len
25. Sjit
26. Djit
27. Sintpkt
28. Dintpkt
29. tcprtt
30. synack
31. ackdat
32. is_sm_ips_ports
33. ct_state_ttl
34. ct_flw_http_mthd
35. is_ftp_login
36. ct_ftp_cmd
37. ct_srv_src
38. ct_srv_dst
39. ct_dst_ltm
40. ct_src_ltm
41. ct_src_dport_ltm
42. ct_dst_sport_ltm
43. ct_dst_src_ltm
44. attack_cat

========================================
DATA TYPES
========================================
sport                 int64
dsport               object
proto                object
state                object
dur                 float64
sbytes                int64
dbytes                int64
sttl                  int64
dttl                  int64
sloss                 int64
dloss                 int64
service              object
Sload               float64
Dload               float64
Spkts                 int64
Dpkts                 int64
swin                  int64
dwin                  int64
stcpb                 int64
dtcpb                 int64
smeansz               int64
dmeansz               int64
trans_depth           int64
res_bdy_len           int64
Sjit                float64
Djit                float64
Sintpkt             float64
Dintpkt             float64
tcprtt              float64
synack              float64
ackdat              float64
is_sm_ips_ports       int64
ct_state_ttl          int64
ct_flw_http_mthd    float64
is_ftp_login        float64
ct_ftp_cmd           object
ct_srv_src            int64
ct_srv_dst            int64
ct_dst_ltm            int64
ct_src_ltm            int64
ct_src_dport_ltm      int64
ct_dst_sport_ltm      int64
ct_dst_src_ltm        int64
attack_cat           object
dtype: object

========================================
CATEGORICAL COLUMNS
========================================
['dsport', 'proto', 'state', 'service', 'ct_ftp_cmd', 'attack_cat']

========================================
NUMERICAL COLUMNS
========================================
Number of numerical columns: 38
['sport', 'dur', 'sbytes', 'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'Sload', 'Dload', 'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz', 'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat', 'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm']

========================================
MISSING VALUES
========================================
is_ftp_login        538455
ct_flw_http_mthd    480568
dtype: int64

========================================
TARGET
========================================
Target column: attack_cat

Training target distribution:
attack_cat
Analysis           20000
Backdoors          20000
DoS               100000
Exploits          100000
Fuzzers           100000
Generic           100000
Normal            100000
Reconnaissance    100000
Shellcode          10000
Worms              10000
Name: count, dtype: int64

Test target distribution:
attack_cat
Analysis             535
Backdoors            466
DoS                 3271
Exploits            8905
Fuzzers             4849
Generic            43096
Normal            443753
Reconnaissance      2798
Shellcode            302
Worms                 35
Name: count, dtype: int64

========================================
STEP 2 COMPLETED
========================================

In [5]:
# ============================================================
# STEP 3: CLEAN + ENCODE UNSW-NB15
# ============================================================

import pandas as pd
import numpy as np
import gc

from sklearn.preprocessing import OrdinalEncoder

print("Starting preprocessing...\n")

# ------------------------------------------------------------
# 1. SEPARATE FEATURES AND TARGET
# ------------------------------------------------------------

X_train = train_df.drop(columns=["attack_cat"]).copy()
y_train = train_df["attack_cat"].copy()

X_test = test_df.drop(columns=["attack_cat"]).copy()
y_test = test_df["attack_cat"].copy()

print("Training features:", X_train.shape)
print("Test features    :", X_test.shape)

# ------------------------------------------------------------
# 2. IDENTIFY CATEGORICAL COLUMNS
# ------------------------------------------------------------

categorical_cols = [
    "dsport",
    "proto",
    "state",
    "service",
    "ct_ftp_cmd"
]

# Everything else is numerical
numerical_cols = [
    col for col in X_train.columns
    if col not in categorical_cols
]

print("\nCategorical columns:")
print(categorical_cols)

print("\nNumerical columns:", len(numerical_cols))

# ------------------------------------------------------------
# 3. CLEAN CATEGORICAL COLUMNS
# ------------------------------------------------------------

print("\nCleaning categorical columns...")

for col in categorical_cols:

    X_train[col] = (
        X_train[col]
        .fillna("missing")
        .astype(str)
        .str.strip()
    )

    X_test[col] = (
        X_test[col]
        .fillna("missing")
        .astype(str)
        .str.strip()
    )

# ------------------------------------------------------------
# 4. CONVERT NUMERICAL COLUMNS TO NUMERIC
# ------------------------------------------------------------

print("Converting numerical columns...")

for col in numerical_cols:

    X_train[col] = pd.to_numeric(
        X_train[col],
        errors="coerce"
    )

    X_test[col] = pd.to_numeric(
        X_test[col],
        errors="coerce"
    )

# ------------------------------------------------------------
# 5. HANDLE INFINITE VALUES
# ------------------------------------------------------------

print("Handling infinite values...")

X_train[numerical_cols] = (
    X_train[numerical_cols]
    .replace([np.inf, -np.inf], np.nan)
)

X_test[numerical_cols] = (
    X_test[numerical_cols]
    .replace([np.inf, -np.inf], np.nan)
)

# ------------------------------------------------------------
# 6. FILL NUMERICAL MISSING VALUES
#    MEDIANS ARE CALCULATED ONLY FROM TRAINING DATA
# ------------------------------------------------------------

print("Filling numerical missing values...")

train_medians = X_train[numerical_cols].median()

X_train[numerical_cols] = (
    X_train[numerical_cols]
    .fillna(train_medians)
)

X_test[numerical_cols] = (
    X_test[numerical_cols]
    .fillna(train_medians)
)

# ------------------------------------------------------------
# 7. ORDINAL ENCODING
# ------------------------------------------------------------

print("Encoding categorical features...")

encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

X_train[categorical_cols] = encoder.fit_transform(
    X_train[categorical_cols]
)

X_test[categorical_cols] = encoder.transform(
    X_test[categorical_cols]
)

# ------------------------------------------------------------
# 8. CONVERT TO FLOAT32
#    REDUCES MEMORY USAGE
# ------------------------------------------------------------

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)

# ------------------------------------------------------------
# 9. RESET INDICES
# ------------------------------------------------------------

X_train.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)

y_train.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)

# ------------------------------------------------------------
# 10. CHECK FOR REMAINING NaN / INF
# ------------------------------------------------------------

print("\n========================================")
print("FINAL DATA CHECK")
print("========================================")

print("Training shape:", X_train.shape)
print("Test shape    :", X_test.shape)

print("\nTraining NaN values:",
      X_train.isna().sum().sum())

print("Test NaN values:",
      X_test.isna().sum().sum())

print("\nTraining infinite values:",
      np.isinf(X_train.to_numpy()).sum())

print("Test infinite values:",
      np.isinf(X_test.to_numpy()).sum())

# ------------------------------------------------------------
# 11. TARGET ENCODING
# ------------------------------------------------------------

class_names = sorted(y_train.unique())

class_to_id = {
    cls: i
    for i, cls in enumerate(class_names)
}

id_to_class = {
    i: cls
    for cls, i in class_to_id.items()
}

y_train_encoded = y_train.map(class_to_id).astype(np.int64)
y_test_encoded = y_test.map(class_to_id).astype(np.int64)

print("\n========================================")
print("CLASS MAPPING")
print("========================================")

for class_id, class_name in id_to_class.items():
    print(f"{class_id}: {class_name}")

# ------------------------------------------------------------
# 12. FINAL SHAPES
# ------------------------------------------------------------

print("\n========================================")
print("PREPROCESSING COMPLETED")
print("========================================")

print("X_train:", X_train.shape)
print("y_train:", y_train_encoded.shape)

print("X_test :", X_test.shape)
print("y_test :", y_test_encoded.shape)

print("\nTraining class IDs:")
print(y_train_encoded.value_counts().sort_index())

print("\nTest class IDs:")
print(y_test_encoded.value_counts().sort_index())

# ------------------------------------------------------------
# 13. FREE ORIGINAL DATAFRAMES
# ------------------------------------------------------------

del train_df
del test_df
del y_train
del y_test
gc.collect()

print("\nOriginal dataframes cleared from memory.")
print("Ready for the next step.")

Starting preprocessing...

Training features: (660000, 43)
Test features    : (508010, 43)

Categorical columns:
['dsport', 'proto', 'state', 'service', 'ct_ftp_cmd']

Numerical columns: 38

Cleaning categorical columns...
Converting numerical columns...
Handling infinite values...
Filling numerical missing values...
Encoding categorical features...

========================================
FINAL DATA CHECK
========================================
Training shape: (660000, 43)
Test shape    : (508010, 43)

Training NaN values: 0
Test NaN values: 0

Training infinite values: 0
Test infinite values: 0

========================================
CLASS MAPPING
========================================
0: Analysis
1: Backdoors
2: DoS
3: Exploits
4: Fuzzers
5: Generic
6: Normal
7: Reconnaissance
8: Shellcode
9: Worms

========================================
PREPROCESSING COMPLETED
========================================
X_train: (660000, 43)
y_train: (660000,)
X_test : (508010, 43)
y_test : (508010,)

Training class IDs:
attack_cat
0     20000
1     20000
2    100000
3    100000
4    100000
5    100000
6    100000
7    100000
8     10000
9     10000
Name: count, dtype: int64

Test class IDs:
attack_cat
0       535
1       466
2      3271
3      8905
4      4849
5     43096
6    443753
7      2798
8       302
9        35
Name: count, dtype: int64

Original dataframes cleared from memory.
Ready for the next step.

In [6]:
# ============================================================
# STEP 4: SAVE PROCESSED DATA
# ============================================================

import os
import pandas as pd
import numpy as np

dataset_path = "/content/drive/MyDrive/UNSW-NB15"

# ------------------------------------------------------------
# 1. CREATE PROCESSED DATAFRAMES
# ------------------------------------------------------------

processed_train = X_train.copy()
processed_train["target"] = y_train_encoded

processed_test = X_test.copy()
processed_test["target"] = y_test_encoded

# ------------------------------------------------------------
# 2. SAVE AS CSV
# ------------------------------------------------------------

processed_train_path = os.path.join(
    dataset_path,
    "UNSW_NB15_processed_train.csv"
)

processed_test_path = os.path.join(
    dataset_path,
    "UNSW_NB15_processed_test.csv"
)

print("Saving processed training data...")

processed_train.to_csv(
    processed_train_path,
    index=False
)

print("Training data saved.")

print("\nSaving processed test data...")

processed_test.to_csv(
    processed_test_path,
    index=False
)

print("Test data saved.")

# ------------------------------------------------------------
# 3. DISPLAY FILE INFORMATION
# ------------------------------------------------------------

print("\n========================================")
print("FILES SAVED")
print("========================================")

print("\nProcessed training:")
print(processed_train_path)

print("\nProcessed test:")
print(processed_test_path)

print("\n========================================")
print("SHAPES")
print("========================================")

print("Processed train:", processed_train.shape)
print("Processed test :", processed_test.shape)

print("\n========================================")
print("TARGET DISTRIBUTION")
print("========================================")

print("\nTraining:")
print(
    processed_train["target"]
    .value_counts()
    .sort_index()
)

print("\nTest:")
print(
    processed_test["target"]
    .value_counts()
    .sort_index()
)

print("\n========================================")
print("STEP 4 COMPLETED")
print("========================================")

Saving processed training data...
Training data saved.

Saving processed test data...
Test data saved.

========================================
FILES SAVED
========================================

Processed training:
/content/drive/MyDrive/UNSW-NB15/UNSW_NB15_processed_train.csv

Processed test:
/content/drive/MyDrive/UNSW-NB15/UNSW_NB15_processed_test.csv

========================================
SHAPES
========================================
Processed train: (660000, 44)
Processed test : (508010, 44)

========================================
TARGET DISTRIBUTION
========================================

Training:
target
0     20000
1     20000
2    100000
3    100000
4    100000
5    100000
6    100000
7    100000
8     10000
9     10000
Name: count, dtype: int64

Test:
target
0       535
1       466
2      3271
3      8905
4      4849
5     43096
6    443753
7      2798
8       302
9        35
Name: count, dtype: int64

========================================
STEP 4 COMPLETED
========================================

In [7]:
import pandas as pd

path = "/content/drive/MyDrive/UNSW-NB15/UNSW_NB15_balanced_train.csv"

df = pd.read_csv(path, usecols=["attack_cat"])

counts = df["attack_cat"].value_counts().sort_index()

print("========================================")
print("BALANCE CHECK")
print("========================================")
print(counts)

print("\n========================================")
print("MIN / MAX")
print("========================================")
print("Minimum class count:", counts.min())
print("Maximum class count:", counts.max())

print("\n========================================")
print("RESULT")
print("========================================")

if counts.nunique() == 1:
    print("✅ PERFECTLY BALANCED")
else:
    print("⚠️ NOT PERFECTLY BALANCED")
    print("\nThis is expected because we intentionally used different")
    print("target sizes for different classes.")

print("\n========================================")
print("PERCENTAGE DISTRIBUTION")
print("========================================")

percentage = (counts / counts.sum() * 100).round(2)

result = pd.DataFrame({
    "Count": counts,
    "Percentage": percentage
})

print(result)

========================================
BALANCE CHECK
========================================
attack_cat
Analysis           20000
Backdoors          20000
DoS               100000
Exploits          100000
Fuzzers           100000
Generic           100000
Normal            100000
Reconnaissance    100000
Shellcode          10000
Worms              10000
Name: count, dtype: int64

========================================
MIN / MAX
========================================
Minimum class count: 10000
Maximum class count: 100000

========================================
RESULT
========================================
⚠️ NOT PERFECTLY BALANCED

This is expected because we intentionally used different
target sizes for different classes.

========================================
PERCENTAGE DISTRIBUTION
========================================
                 Count  Percentage
attack_cat
Analysis         20000        3.03
Backdoors        20000        3.03
DoS             100000       15.15
Exploits        100000       15.15
Fuzzers         100000       15.15
Generic         100000       15.15
Normal          100000       15.15
Reconnaissance  100000       15.15
Shellcode        10000        1.52
Worms            10000        1.52